# Modify your global configuration here. You can find all config items in the
# templates folder.

Dir:
  local_config_file: ./config/config.yaml
  procedures_file: ./config/procedures.yaml
  sequences_file: ./config/sequences.yaml
  instruments_file: ./config/instruments.yaml
